In [ ]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder


df = pd.read_csv("../../data/raw/dataset_practica_final.csv")

df.info()
df.isna().sum()
columnas_numericas = ['children', 'agent', 'company']
imputer_numerico = SimpleImputer(strategy="mean")
df[columnas_numericas] = imputer_numerico.fit_transform(df[columnas_numericas])

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

In [55]:
df.isna().sum()
columna_categorica = ['country']
imputer_country = SimpleImputer(strategy="constant", fill_value="undefined")
df[columna_categorica] = imputer_country.fit_transform(df[columna_categorica])

In [56]:
columna_target = 'is_canceled'
df_preprocessed = df.drop(columns=[columna_target])
df_preprocessed.info()
df_preprocessed.describe().transpose()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   lead_time                       119390 non-null  int64
 2   arrival_date_year               119390 non-null  int64
 3   arrival_date_month              119390 non-null  str
 4   arrival_date_week_number        119390 non-null  int64
 5   arrival_date_day_of_month       119390 non-null  int64
 6   stays_in_weekend_nights         119390 non-null  int64
 7   stays_in_week_nights            119390 non-null  int64
 8   adults                          119390 non-null  int64
 9   children                        119390 non-null  float64
 10  babies                          119390 non-null  int64
 11  meal                            119390 non-null  str
 12  country                         119390 non-null  str
 13  market_segment                  119390 non-null  str
 14  distribution_channel            119390 non-null  str
 15  is_repeated_guest               119390 non-null  int64
 16  previous_cancellations          119390 non-null  int64
 17  previous_bookings_not_canceled  119390 non-null  int64
 18  reserved_room_type              119390 non-null  str
 19  assigned_room_type              119390 non-null  str
 20  booking_changes                 119390 non-null  int64
 21  deposit_type                    119390 non-null  str
 22  agent                           119390 non-null  float64
 23  company                         119390 non-null  float64
 24  days_in_waiting_list            119390 non-null  int64
 25  customer_type                   119390 non-null  str
 26  adr                             119390 non-null  float64
 27  required_car_parking_spaces     119390 non-null  int64
 28  total_of_special_requests       119390 non-null  int64
 29  reservation_status              119390 non-null  str
 30  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(15), str(12)
memory usage: 28.2 MB

,count,mean,std,min,25%,50%,75%,max
lead_time,119390.0,104.011416,106.863097,0.00,18.000000,69.000000,160.000000,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.000000,2016.000000,2017.000000,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.000000,28.000000,38.000000,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.000000,16.000000,23.000000,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.000000,1.000000,2.000000,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.000000,2.000000,3.000000,50.0
adults,119390.0,1.856403,0.579261,0.00,2.000000,2.000000,2.000000,55.0
children,119390.0,0.103890,0.398555,0.00,0.000000,0.000000,0.000000,10.0
babies,119390.0,0.007949,0.097436,0.00,0.000000,0.000000,0.000000,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.000000,0.000000,0.000000,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.000000,0.000000,0.000000,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.000000,0.000000,0.000000,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.000000,0.000000,0.000000,21.0
agent,119390.0,86.693382,102.915247,1.00,9.000000,28.000000,152.000000,535.0
company,119390.0,189.266735,31.411012,6.00,189.266735,189.266735,189.266735,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.000000,0.000000,0.000000,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.290000,94.575000,126.000000,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.000000,0.000000,0.000000,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.000000,0.000000,1.000000,5.0

In [57]:
columnas_categoricas = ['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment', 'distribution_channel', 'reserved_room_type', 'deposit_type', 'customer_type', 'assigned_room_type', 'reservation_status', 'reservation_status_date']
encoder = OneHotEncoder(sparse_output=False)

df_encoded = pd.DataFrame(
    encoder.fit_transform(df_preprocessed[columnas_categoricas]),
    columns=encoder.get_feature_names_out(columnas_categoricas)
)
df_encoded.columns = df_encoded.columns.str.lower()

df_final = pd.concat(
    [df_preprocessed.drop(columns=columnas_categoricas), df_encoded],
    axis=1
)

In [58]:
todas_las_columnas_numericas = df_preprocessed.select_dtypes(include=['number']).columns
scaler = StandardScaler()
df_preprocessed[todas_las_columnas_numericas] = scaler.fit_transform(df[todas_las_columnas_numericas])

In [59]:
df_final.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
lead_time,119390.0,104.011416,106.863097,0.0,18.0,69.0,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.0,2016.0,2016.0,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.0,16.0,28.0,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.0,8.0,16.0,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.0,0.0,1.0,2.0,19.0
...,...,...,...,...,...,...,...,...
reservation_status_date_2017-09-08,119390.0,0.000034,0.005788,0.0,0.0,0.0,0.0,1.0
reservation_status_date_2017-09-09,119390.0,0.000050,0.007089,0.0,0.0,0.0,0.0,1.0
reservation_status_date_2017-09-10,119390.0,0.000034,0.005788,0.0,0.0,0.0,0.0,1.0
reservation_status_date_2017-09-12,119390.0,0.000008,0.002894,0.0,0.0,0.0,0.0,1.0
reservation_status_date_2017-09-14,119390.0,0.000017,0.004093,0.0,0.0,0.0,0.0,1.0